name: NPM Audit

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    paths:
      - 'package.json'
      - 'package-lock.json'

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check for new vulnerabilities
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
        with:
          fail-on-severity: high
          fail-on-scopes: unknown, runtime, development
          comment-summary-in-pr: never
